  # This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: doxy-helm

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: pip install --upgrade pip && pip install -r requirements.txt

    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: run unit-tests
      run: |
        python -m unittest discover -s ./tests/unit-test/

    - name: run test the full functionality of the tool
      run: |
        python -m unittest discover -s ./tests/end-test/ 
